lcm_mafia:
    resource: "@LCMMafiaBundle/Controller/"
    type:     annotation
    prefix:   /mafia

lcm_admin:
    resource: "@LCMAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

lcm_core:
    resource: "@LCMCoreBundle/Controller/"
    type:     annotation
    prefix:   /

_security_check:
    pattern:  /mafia/login_check

_security_logout:
    pattern:  /mafia/logout

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /mafia/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /mafia/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /mafia/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /mafia/profile

fos_user_security_login:
    pattern:  /mafia/login
    
fos_user_security_logout:
    pattern:  /mafia/logout

lcm_core_default_checks:
    pattern:  /mafia/login_check

fos_user_security_check:
    pattern:  /mafia/login_check



fos_facebook_channel:
    resource: "@FOSFacebookBundle/Resources/config/routing.xml"