security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [my_fos_facebook_provider]
        fos_userbundle:
            id: fos_user.user_provider.username
        my_fos_facebook_provider:
            id: my.facebook.user

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        public:
            pattern:   ^/mafia/*|^/admin/*
            fos_facebook:
                login_path: /login
                check_path: /mafia/login_check
                default_target_path: /
                provider: my_fos_facebook_provider
            anonymous: true
            logout: true
        

    access_control:
        - { path: ^/mafia/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mafia/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mafia/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mafia/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin*, role: ROLE_ADMIN }
        - { path: ^/mafia*, role: [ROLE_FACEBOOK] }
        